unmatched_resources = [   
    {   'ResourceCategory': 'Init',
        'ResourceID': 'IMAGE_BLANK',
        'ResourcePath': 'resources/images/blank_.gif',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_CONE1',
        'ResourcePath': 'resources/zombies/zombie/cone1.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_CONE2',
        'ResourcePath': 'resources/zombies/zombie/cone2.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_CONE3',
        'ResourcePath': 'resources/zombies/zombie/cone3.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_BUCKET1',
        'ResourcePath': 'resources/zombies/zombie/bucket1.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_BUCKET2',
        'ResourcePath': 'resources/zombies/zombie/bucket2.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_BUCKET3',
        'ResourcePath': 'resources/zombies/zombie/bucket3.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_SCREENDOOR1',
        'ResourcePath': 'resources/zombies/zombie/screendoor1.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_SCREENDOOR2',
        'ResourcePath': 'resources/zombies/zombie/screendoor2.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_SCREENDOOR3',
        'ResourcePath': 'resources/zombies/zombie/screendoor3.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_FLAG1',
        'ResourcePath': 'resources/zombies/zombie/flag1.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_FLAG3',
        'ResourcePath': 'resources/zombies/zombie/flag3.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_OUTERARM_UPPER2',
        'ResourcePath': 'resources/zombies/zombie/outerarm_upper2.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_OUTERARM_HAND',
        'ResourcePath': 'resources/zombies/zombie/outerarm_hand.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_HEAD_GROSSOUT',
        'ResourcePath': 'resources/zombies/zombie/head_grossout.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES1',
        'ResourcePath': 'resources/zombies/zombie/head_sunglasses1.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES2',
        'ResourcePath': 'resources/zombies/zombie/head_sunglasses2.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES3',
        'ResourcePath': 'resources/zombies/zombie/head_sunglasses3.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES4',
        'ResourcePath': 'resources/zombies/zombie/head_sunglasses4.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_MUSTACHE2',
        'ResourcePath': 'resources/zombies/zombie/mustache2.png',
        'ResourceType': 'Image'},
    {   'ResourceCategory': 'LoadingImages',
        'ResourceID': 'IMAGE_REANIM_ZOMBIE_MUSTACHE3',
        'ResourcePath': 'resources/zombies/zombie/mustache3.png',
        'ResourceType': 'Image'}]